name: "dbt_lena"
version: "1.0.0"
config-version: 2

profile: "lena_research"

quoting:
  database: true
  schema: true
  identifier: true

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data", "eda_data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

seeds:
  +quote_columns: true
  +schema: "seed"

models:
  dbt_lena:
    eda:
      +tags: ["eda"]
      +materialized: "table"
      +schema: "eda"
    stg_eda:
      +tags: ["staging"]
      +materialized: "ephemeral"
      +schema: "staging"
